services:
  postgres:
    container_name: postgres
    image: 'postgres:15.3'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=product-discount-service'
      - 'PGDATA=/data/postgres'
    volumes:
      - 'postgres:/data/postgres'
    ports:
      - '5432:5432'
    restart: always
    networks:
      - 'postgres'
  pgadmin:
    container_name: pgadmin
    image: 'dpage/pgadmin4'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - 'pgadmin:/var/lib/pgadmin'
    ports:
      - '5050:80'
    networks:
      - 'postgres'

volumes:
  postgres:
  pgadmin:

networks:
    postgres:
      driver: bridge
